#!/bin/sh

### Loads on X server start

# Wallpaper
setwall &

# Remaps: caps to escape, keyboard layout switch, etc
xinit-remaps &

# Daemons: dunst, sxhkd, picom, etc
xinit-daemons &

# Restart daemons on config change
#xinit-config-hot-updaters &

# Load Xresources database
xrdb -I"$HOME" "${XDG_CONFIG_HOME:-$HOME/.config}/x11/xresources"

# Choose your Window Manager...
exec xmonad 
#exec dwm 
