#!/bin/sh

### Loads on X server start

set -u

# Load Xresources database
xrdb -I"${HOME}" "${XDG_CONFIG_HOME:-${HOME}/.config}/x11/xresources"

# Export environment variables to session
export XDG_SESSION_TYPE="X11"
export QT_QPA_PLATFORM=wayland
export MOZ_ENABLE_WAYLAND=0
export XDG_CURRENT_DESKTOP=xmonad:gnome
export XDG_SESSION_TYPE=X11
export TERMCMD=st
export TERMINAL=st
export MENU=dmenu
export BEMENU_BACKEND=x11
export ENVRUND_HOME="${XDG_RUNTIME_DIR}/envrund/tty2"

session -s "tty2" \
  import \
  'ENVRUND_HOME' \
  'DISPLAY' \
  'QT_QPA_PLATFORM' \
  'MOZ_ENABLE_WAYLAND' \
  'XDG_CURRENT_DESKTOP' \
  'XDG_SESSION_TYPE' \
  'TERMCMD' \
  'TERMINAL' \
  'MENU' \
  'BEMENU_BACKEND'

# Tell my systemd services that they can start
command -v systemctl >/dev/null 2>&1 \
  && systemctl --user start "graphical-session@tty2.target" >/dev/null 2>&1

# Start WM
"${HOME}/.xmonad/xmonad-x86_64-linux"

session -s "tty2" \
  unset \
  'DISPLAY' \
  'QT_QPA_PLATFORM' \
  'MOZ_ENABLE_WAYLAND' \
  'XDG_CURRENT_DESKTOP' \
  'XDG_SESSION_TYPE' \
  'TERMCMD' \
  'TERMINAL' \
  'MENU' \
  'BEMENU_BACKEND'

# Tell my systemd services that they no longer can run
command -v systemctl >/dev/null 2>&1 \
  && systemctl --user stop "graphical-session@tty2.target" >/dev/null 2>&1
