#!/bin/sh

clamp() {
	min="${1}"
	max="${2}"
	val="${3}"
  [ $(cl "${val} > ${max}") ] && val="${max}"
  [ $(cl "${val} < ${min}") ] && val="${min}"
}

workspaces_count="$(hyprctl workspaces -j | gojq 'length')"

direction="$1"
current="$2"

case "${direction}" in
  'down') ;;
  'up') ;;
esac

if test "${direction}" = "down"
then
  target="$(( (current + 1) % workspaces_count ))"
	echo "jumping to $target"
	hyprctl dispatch workspace "${target}"
elif test "${direction}" = "up"
then
	target="$(( (current + 1) % workspaces_count))"
	echo "jumping to $target"
	hyprctl dispatch workspace "${target}"
fi
