#!/bin/sh

spaces (){
	WORKSPACE_WINDOWS=$(hyprctl workspaces -j | gojq 'map({key: .id | tostring, value: .windows}) | from_entries')
	seq 1 10 | gojq --argjson windows "${WORKSPACE_WINDOWS}" --slurp -Mc 'map(tostring) | map({id: ., windows: ($windows[.]//0)})'
}

spaces
socat -u "UNIX-CONNECT:/tmp/hypr/${HYPRLAND_INSTANCE_SIGNATURE}/.socket2.sock" '-' | while read -r _; do
	spaces
done
