#!/bin/sh

#### XDG stuff ====================================

# Taken from https://wiki.archlinux.org/index.php/XDG_Base_Directory
export XDG_CONFIG_HOME=$HOME/.config
export XDG_CACHE_HOME=$HOME/.cache
export XDG_DATA_HOME=$HOME/.local/share
export XDG_DATA_DIRS=/usr/local/share:/usr/share
export XDG_CONFIG_DIRS=/etc/xdg
 
### Shell history stuff ===========================

HISTFILE=$XDG_CONFIG_HOME/zsh/.zhistory
HISTSIZE=1000000
SAVEHIST=1000000

### Path stuff ====================================
# Add binaries from HOME
export PATH="$HOME/.local/bin":$PATH
# Make nvim open man pages 
[ -x /bin/nvim ] && export MANPAGER='nvim +Man!'
export MANWIDTH=999
# Add Rust modules 
export PATH=$HOME/.cargo/bin:$PATH
# Add GO modules
export PATH=$HOME/.local/share/go/bin:$PATH
# Add miniconda
export PATH=$HOME/.miniconda/bin:$PATH

### Systemwide stuff ==============================

# Default EDITOR
[ -x /usr/bin/nvim ] && export EDITOR=/usr/bin/nvim

# Truecolor
# Turned out to be unnecessary with `st`
# export TERM="xterm-256color"

# Less color
export LESS='-R --use-color -Dd+r$Du+b'
export LESSOPEN="| /usr/bin/source-highlight-esc.sh %s"

### Language-specific stuff =======================

# Setup DotNet
export DOTNET_CLI_TELEMETRY_OPTOUT=1

# Setup GO
export GOPATH=$HOME/.local/share/go

# Setup Rust
[ -s $HOME/.cargo/env ] && source $HOME/.cargo/env

# Setup Haskell
export PATH="$HOME/.stack/bin:$HOME/.cabal/bin:$HOME/.ghcup/bin:$PATH"

# Setup NVM
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

# Setup PyEnv
export PYENV_ROOT="$HOME/.pyenv"
export PATH="$PYENV_ROOT/bin:$PATH"

#eval "$(fnm env)"
#eval "$(zoxide init zsh)"
#eval "`pip completion --zsh`"
