#!/bin/bash

# Functions necessary to run this config
source "${ZDOTDIR}/zsh_functions"

### Source all config files

# All of below depend on `zsh_functions`

zsh_add_file "zsh_exports"

################################################
       ### PEEPOS, first of all...
 [[ -o login ]] && random-pepe 2>/dev/null
################################################

# Continue normally with mundane stuff...
zsh_add_file "zsh_options"
zsh_add_file "zsh_aliases"
zsh_add_file "zsh_prompt"
zsh_add_file "zsh_vim_mode"
zsh_add_file "zsh_keybindings"
zsh_add_file "zsh_plugins"

### Load zsh modules =================

# Enable zsh's profiling module
zmodload zsh/zprof

# Enable pywal colors in terminal by pasting 
# it's escape sequences
(cat ~/.cache/wal/sequences &)

### Start X on login

RED='\033[0;31m'
NC='\033[0m' # No Color

ERROR="${RED}ERROR: ${NC}"

# Start/source ssh-agent
if ! pgrep -u "${USER}" ssh-agent > /dev/null; then
  [ ! -d "${XDG_RUNTIME_DIR}" ] && mkdir -p "${XDG_RUNTIME_DIR}"
  ssh-agent -t 744h > "${XDG_RUNTIME_DIR}/ssh-agent.env"
fi
if [[ ! "$SSH_AUTH_SOCK" ]]; then
  # shellcheck disable=1091
  source "${XDG_RUNTIME_DIR}/ssh-agent.env" >/dev/null
fi

# Start X server if in tty1 and X server isn't running
maybe_startx () {

  # Continue to the terminal if in the pseudo terminal, not TTY
  tty | grep -q '^/dev/pts' && return

  echo "Starting X server...";

  # Trow to shell if not on first TTY
  if [ ! "$(tty)" = '/dev/tty1' ]; then
    echo "${ERROR}You are not in the first TTY. X server won't start."
    echo "Leaving you in the shell."
    return;
  fi

  # Throw to shell if `DISPLAY` is already set
  # shellcheck disable=2237
  if ! [ -z "${DISPLAY}" ]; then
    echo "${ERROR}ERROR: \`DISPLAY\` is already set. X server already running on this TTY and you seeng this message. Something wrong."
    echo "Leaving you in the shell."
    return
  fi

  # Throw to shell if `startx` is missing
  if [ ! -x /bin/startx ]; then
    echo "${ERROR}: Seems like the X server is not installed or not properly installed: \`startx\` is not in your \`PATH\`. X server won't start."
    echo "Leaving you in the shell."
    return
  fi

  LOGDIR="${XDG_DATA_HOME}/xinitrc"

  [ ! -d "${LOGDIR}" ] && (mkdir "${LOGDIR}"; echo 'This is a custom `.xinitrc` log location. See `maybe_startx` in `~/.config/zsh/zshrc`' > "${LOGDIR}/README.md")
  exec startx "${XDG_CONFIG_HOME}/x11/xinitrc" >>"${LOGDIR}/xinitrc.error.log" 2>>"${LOGDIR}/xinitrc.error.log"
}

# Only start if `DISPLAY == "" && tty == tty1 && startx`
maybe_startx
