#!/bin/sh

# Functions necessary to setup this config
source "$ZDOTDIR/zsh_functions"

# Normal files to source
zsh_add_file "zsh_exports"
zsh_add_file "zsh_options"
zsh_add_file "zsh_aliases"
zsh_add_file "zsh_prompt"
zsh_add_file "zsh_vim_mode"
zsh_add_file "zsh_keybindings"
zsh_add_file "zsh_plugins"

# FZF
#source /usr/share/fzf/key-bindings.zsh
#source /usr/share/fzf/completion.zsh
#export FZF_DEFAULT_COMMAND='rg --hidden -l ""'

