#!/bin/sh

# Functions necessary to run this config
source "$ZDOTDIR/zsh_functions"

### Source all the files

# They all depend on `zsh_functions`
zsh_add_file "zsh_exports"
zsh_add_file "zsh_options"
zsh_add_file "zsh_aliases"
zsh_add_file "zsh_prompt"
zsh_add_file "zsh_vim_mode"
zsh_add_file "zsh_keybindings"
zsh_add_file "zsh_plugins"

### Load ZSH modules

# Enable profiling
zmodload zsh/zprof

### Start X on login

# Only start if DISPLAY == "" && XDG_VTNR == 1
[[ -z $DISPLAY && $XDG_VTNR -eq 1 ]] && exec startx > /dev/null 2>&1

# FZF
#source /usr/share/fzf/key-bindings.zsh
#source /usr/share/fzf/completion.zsh
#export FZF_DEFAULT_COMMAND='rg --hidden -l ""'

